ALTER TABLE IF EXISTS APPLICATION_ADVICE ADD COLUMN CUSTOM_TASK_ATTRIBUTES JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS PARTIES ADD COLUMN CUSTOM_ATTRIBUTES JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS SUBSCRIBERS ADD COLUMN CUSTOM_ATTRIBUTES JSONB NOT NULL DEFAULT '{}'::jsonb;